[phases.setup]
nixPkgs = ['openjdk17', 'maven']

[start]
cmd = "cd demo && java -jar target/SocietyParking.jar"



[build]
cmd = ["cd demo && mvn clean package -DskipTests",
"cp demo/target/SocietyParking.jar ."
    ]
