[providers]
packages = ["openjdk17", "maven"]

[phases.build]
cmds = [
    "cd demo && mvn clean package -DskipTests",
    "cp demo/target/SocietyParking.jar ."
]

[start]
cmd = "java -jar SocietyParking.jar"
