spring.application.name=ParkingApplication

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:51273/railway

spring.datasource.username=root
spring.datasource.password=hQKIfclivUVzfKGDUePHdCOYhCETIhMk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dkfacts8@gmail.com
spring.mail.password=qaxjduccxgvgidby
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework=DEBUG
logging.level.com.society=DEBUG


server.port=8080
server.address=0.0.0.0
